# Generated by Django 4.0.2 on 2022-04-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('modules', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('platformid', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.FileField(default='default.jpg', upload_to='images')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('tutorialid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos')),
                ('description', models.CharField(max_length=200)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.courses')),
                ('platformid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform')),
            ],
        ),
        migrations.CreateModel(
            name='project_table',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('documentation', models.CharField(max_length=400)),
                ('project', models.FileField(upload_to='projects')),
                ('userid', models.CharField(default=1, max_length=500)),
                ('platformid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform')),
            ],
        ),
        migrations.CreateModel(
            name='mcq',
            fields=[
                ('mcqid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=30)),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('option4', models.CharField(max_length=30)),
                ('platformid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='platformid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform'),
        ),
        migrations.CreateModel(
            name='coursemcq',
            fields=[
                ('mcqid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=30)),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('option4', models.CharField(max_length=30)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.courses')),
            ],
        ),
    ]
