# Generated by Django 4.0.2 on 2022-03-29 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='platform',
            fields=[
                ('platformid', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('image', models.FileField(default='default.jpg', upload_to='images')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project_table',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('documentation', models.CharField(max_length=50)),
                ('project', models.FileField(upload_to='projects')),
                ('platformid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform')),
            ],
        ),
    ]
