# Generated by Django 4.0.2 on 2022-03-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='platform',
            fields=[
                ('platformid', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('image', models.FileField(default='default.jpg', upload_to='images')),
                ('adminid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.admin_reg')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('documentation', models.CharField(max_length=50)),
                ('project', models.FileField(upload_to='projects')),
                ('platformid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform')),
            ],
        ),
    ]
