# Generated by Django 4.0.2 on 2022-04-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project_table',
        ),
    ]
