# Generated by Django 4.0.2 on 2022-04-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0002_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project_table',
            name='documentation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project_table',
            name='project_name',
            field=models.CharField(max_length=50),
        ),
    ]
