# Generated by Django 4.0.2 on 2022-03-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0002_platform_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='project_table',
        ),
    ]
