# Generated by Django 4.0.2 on 2022-04-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0004_alter_platform_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('modules', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('platformid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform')),
            ],
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('tutorialid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos')),
                ('description', models.CharField(max_length=200)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.courses')),
            ],
        ),
        migrations.CreateModel(
            name='coursemcq',
            fields=[
                ('mcqid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=30)),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('option4', models.CharField(max_length=30)),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.courses')),
            ],
        ),
    ]
