# Generated by Django 4.0.2 on 2022-04-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0004_alter_project_table_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project_table',
        ),
    ]
