# Generated by Django 4.0.2 on 2022-04-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0005_courses_tutorial_coursemcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='coursename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='modules',
            field=models.CharField(max_length=50),
        ),
    ]
