# Generated by Django 4.0.2 on 2022-04-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0006_alter_courses_coursename_alter_courses_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='Name',
            new_name='name',
        ),
    ]
