# Generated by Django 4.0.2 on 2022-04-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0007_rename_name_tutorial_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='platformid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_mod.platform'),
        ),
    ]
