# Generated by Django 4.0.2 on 2022-04-08 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('userprofileid', models.AutoField(primary_key=True, serialize=False)),
                ('usertype', models.CharField(max_length=20)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('detailid', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=10)),
                ('companyinstitution', models.CharField(max_length=30)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='clientproject',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=30)),
                ('detailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mod.userdetails')),
            ],
        ),
    ]
